services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    networks:
      - ocr-network
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "7601:7601"
    volumes:
      - ./output:/app/output
    depends_on:
      - fastapi
    networks:
      - ocr-network
    environment:
      - PYTHONUNBUFFERED=1

networks:
  ocr-network:
    driver: bridge

volumes:
  output:
    driver: local