version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./output:/app/output
    networks:
      - ocr-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "7601:7601"
    volumes:
      - ./output:/app/output
    depends_on:
      - fastapi
    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge